Repository rnbwdev/rnbw, pull requests merged in 2023-11, with the labels that each got.

#332 331 group and ungroup
  src/components/main/actionsPanel/nodeTreeView/helpers/helpers.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
Labels: enhancement

#333 #311 - Identifying new focused node
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts
  src/components/main/codeView/CodeView.tsx
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/stageView/iFrame/hooks/useTextEditing.ts
Labels: enhancement

#335 feat: Paste text that is html and turn it into nodes
  src/components/main/stageView/iFrame/hooks/useTextEditing.ts
Labels: enhancement

#338 rnbw-315: Delete action is performed by pressing any of the Delete or Backspace keys
  src/_ref/cmdk.ref/Actions.csv
  src/components/main/stageView/iFrame/hooks/useCmdk.ts
  src/pages/main/MainPage.tsx
  src/types/main.ts
Labels: enhancement

#339 fix: #336
  src/components/main/actionsPanel/ActionsPanel.tsx
  src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx
  src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx
Labels: bug

#352 348 - Fixed options showing
  src/pages/main/MainPage.tsx
Labels: bug

#353 rnbw-340: Implemented new node adding
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
Labels: enhancement

#359 feat: no code segment highlighting when CodeView is focused.
  src/components/main/codeView/CodeView.tsx
  src/components/main/codeView/hooks/useEditor.tsx
Labels: enhancement

#360 rnbw-351: Fixed selection first node and expanding tree
  src/components/main/actionsPanel/navigatorPanel/helpers/helpers.ts
  src/components/main/actionsPanel/navigatorPanel/hooks/useFavicon.ts
Labels: bug

#364 feat: web components now don't get refreshed link, script tags are no longer removed on morphing via morphdom
  src/components/common/loader/Loader.tsx
  src/components/main/actionsPanel/navigatorPanel/helpers/helpers.ts
  src/components/main/actionsPanel/navigatorPanel/hooks/useFavicon.ts
  src/components/main/actionsPanel/nodeTreeView/helpers/creatingNode.ts
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/processor/hooks/useProcessorUpdateOpt.ts
  src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
Labels: enhancement

#375 rnbw-371: Node updating after typing
  src/components/main/actionsPanel/navigatorPanel/helpers/helpers.ts
  src/components/main/actionsPanel/navigatorPanel/hooks/useFavicon.ts
Labels: bug

#378 rnbw-358: Stage link opening
  src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
Labels: bug

#387 feat: extension now works and so the editor wrapping
  src/components/main/codeView/hooks/useEditor.tsx
Labels: bug

#389 rnbw-357: Code formatting after actions
  package.json
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
Labels: enhancement

#392 #391
  src/_node/file/handlers/constants.ts
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/stageView/iFrame/IFrame.tsx
  src/services/htmlapi.ts
Labels: bug

#398 callNodeApi
  package-lock.json
  src/_node/apis.ts
  src/_node/file/actions.ts
  src/_node/file/handlers/handlers.ts
  src/_node/file/index.ts
  src/_node/helpers.ts
  src/_node/html/index.ts
  src/_node/index.ts
  src/_node/node/actions.ts
  src/_node/node/index.ts
  src/_node/node/type/html.ts
  src/_node/node/type/index.ts
  src/components/main/actionsPanel/navigatorPanel/helpers/helpers.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeViewState.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeViewState.ts
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/processor/helpers/helpers.ts
  src/components/main/processor/hooks/useProcessorNodeTree.ts
  src/components/main/stageView/iFrame/helpers/createAndInsertElement.ts
  src/components/main/stageView/iFrame/helpers/handleElementClick.ts
  src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
  src/components/main/stageView/iFrame/hooks/useTextEditing.ts
  src/pages/main/MainPage.tsx
  src/services/htmlapi.ts
Labels: @code, enhancement, @stage, @actions

#400 integrating callNodeApi
  src/_node/apis.ts
  src/_node/file/actions.ts
  src/_node/file/apis.ts
  src/_node/node/actions.ts
  src/_node/types.ts
  src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx
  src/components/main/actionsPanel/nodeTreeView/helpers/helpers.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useCmdk.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHandlers.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeTreeCallback.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/components/main/codeView/CodeView.tsx
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/codeView/types.ts
  src/components/main/processor/helpers/helpers.ts
  src/components/main/processor/hooks/useProcessorUpdate.ts
  src/components/main/stageView/iFrame/hooks/useTextEditing.ts
  src/constants/main.ts
Labels: @code, enhancement, @html, @stage, @actions

#403 Fixed selection from stage
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
Labels: bug

#432 Disable style tag morphing
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/processor/hooks/useProcessorUpdate.ts
Labels: bug

#433 feat: Undefined showing in file name
  src/_node/file/apis.ts
  src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx
Labels: bug

#424 File System
  src/_node/file/actions.ts
  src/_node/file/constants.ts
  src/_node/file/helpers.ts
  src/_node/file/index.ts
  src/_node/file/types.ts
  src/_node/node/index.ts
  src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx
  src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useFileOperations.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useInvalidNodes.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeViewState.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useTemporaryNodes.ts
Labels: @files, enhancement, @actions

#451 #430
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeViewState.ts
  src/components/main/index.ts
  src/components/main/processor/Processor.tsx
  src/components/main/processor/hooks/index.ts
  src/components/main/processor/hooks/useProcessorNodeTree.ts
  src/components/main/processor/hooks/useProcessorValidNodeTree.ts
  src/components/main/processor/index.ts
  src/components/main/processor/types.ts
  src/pages/main/MainPage.tsx
  src/pages/main/processor/helpers/helpers.ts
  src/pages/main/processor/helpers/index.ts
  src/pages/main/processor/hooks/index.ts
  src/pages/main/processor/hooks/useFileTreeEvent.ts
  src/pages/main/processor/hooks/useHms.ts
  src/pages/main/processor/hooks/useNodeTreeEvent.ts
  src/pages/main/processor/hooks/useSaveCommand.ts
  src/pages/main/processor/index.ts
  src/pages/main/processor/useProcessor.ts
Labels: enhancement
