Repository rnbwdev/rnbw, pull requests merged in 2023-10, with the labels that each got.

#307 #303 improve parsing
  package-lock.json
  package.json
  src/_node/apis.ts
  src/_node/file/apis.ts
  src/_node/html/apis.ts
  src/_node/html/types.ts
  src/_redux/main/context.ts
  src/_redux/main/slice.ts
  src/_redux/main/types.ts
  src/components/main/actionsPanel/nodeTreeView/helpers/creatingNode.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/codeView/CodeView.tsx
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/codeView/hooks/useEditorWrapper.tsx
  src/components/main/process/Process.tsx
  src/components/main/process/helpers/helpers.ts
  src/components/main/process/hooks/index.ts
  src/components/main/process/hooks/useAppTitle.ts
  src/components/main/process/hooks/useProcessorUpdateOpt.ts
  src/pages/main/MainPage.tsx
Labels: enhancement

#309 #303 improve parser
  package-lock.json
  package.json
  src/_node/html/apis.ts
  src/_node/html/types.ts
  src/components/main/codeView/CodeView.tsx
  src/components/main/codeView/hooks/useEditor.tsx
Labels: enhancement

#314 310 invalid html parsing
  package-lock.json
  package.json
  src/_node/apis.ts
  src/_node/file/apis.ts
  src/_node/html/apis.ts
  src/_node/html/types.ts
  src/_node/types.ts
  src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx
  src/components/main/actionsPanel/nodeTreeView/helpers/creatingNode.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/components/main/codeView/CodeView.tsx
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/process/helpers/helpers.ts
  src/components/main/process/hooks/useProcessorUpdateOpt.ts
  src/components/main/stageView/iFrame/helpers/handleElementClick.ts
  src/components/main/stageView/iFrame/hooks/useTextEditing.ts
Labels: enhancement

#321 rnbw-316: Multiple selecting from stage
  src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
Labels: bug

#322 #305
  src/_redux/main/context.ts
  src/_redux/main/types.ts
  src/components/main/actionsPanel/ActionsPanel.tsx
  src/components/main/codeView/CodeView.tsx
  src/components/main/codeView/hooks/useEditor.tsx
  src/components/main/process/helpers/helpers.ts
  src/components/main/process/hooks/useProcessorUpdateOpt.ts
  src/components/main/stageView/iFrame/IFrame.tsx
  src/components/main/stageView/iFrame/hooks/useTextEditing.ts
  src/pages/main/MainPage.tsx
Labels: enhancement, bug

#327 rnbw-319: Implementing cut-paste
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
Labels: bug

#329 rnbw-324: Implementing nodes duplication
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
Labels: enhancement, bug

#330 rnbw-325: Implementing drag and drop
  src/components/main/actionsPanel/nodeTreeView/helpers/helpers.ts
  src/components/main/actionsPanel/nodeTreeView/helpers/index.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeTreeCallback.ts
Labels: enhancement
