Repository rnbwdev/rnbw, pull requests merged in 2023-12, with the labels that each got.

#471 Bugs
  src/components/main/actionsPanel/navigatorPanel/helpers/helpers.ts
  src/components/main/stageView/iFrame/hooks/useCmdk.ts
  src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
  src/pages/main/processor/helpers.ts
  src/pages/main/processor/hooks/useNodeTreeEvent.ts
Labels: bug

#475 #472
  src/_node/file/handlers/handlers.ts
  src/_node/node/actions.ts
  src/_node/node/helpers.ts
  src/_node/node/types.ts
  src/_node/types.ts
  src/components/main/actionsPanel/navigatorPanel/hooks/useNavigatorPanelHandlers.ts
  src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx
  src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx
  src/components/main/stageView/StageView.tsx
  src/components/main/stageView/iFrame/IFrame.tsx
  src/components/main/stageView/iFrame/helpers.ts
  src/components/main/stageView/iFrame/hooks/useCmdk.ts
  src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
  src/components/main/stageView/iFrame/hooks/useSyncNode.ts
  src/constants/main.ts
  src/pages/main/MainPage.tsx
  src/pages/main/processor/hooks/useNodeTreeEvent.ts
  src/pages/main/processor/hooks/useSaveCommand.ts
Labels: enhancement, bug, @stage

#482 Merge pull request #479 from rnbwdev/dev
  src/_redux/main/nodeTree/event/constants.ts
  src/_redux/main/nodeTree/event/slice.ts
  src/_redux/main/nodeTree/slice.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeViewState.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/components/main/stageView/iFrame/hooks/useCmdk.ts
  src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
  src/pages/main/MainPage.tsx
  src/pages/main/helper.ts
  src/pages/main/processor/hooks/useNodeTreeEvent.ts
Labels: enhancement

#489 Fix file change confirmation logic
  src/_node/file/handlers/handlers.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/pages/main/MainPage.tsx
  src/pages/main/processor/helpers.ts
Labels: enhancement

#509 #505
  src/_node/file/FileSystemApis.ts
  src/_node/file/actions.ts
  src/_node/file/apis.ts
  src/_node/file/helpers.ts
  src/_node/file/types.ts
  src/_node/helpers.ts
  src/_redux/main/cmdk/constants.ts
  src/_redux/main/cmdk/index.ts
  src/_redux/main/codeView/constants.ts
  src/_redux/main/codeView/index.ts
  src/_redux/main/context.ts
  src/_redux/main/fileTree/constants.ts
  src/_redux/main/fileTree/event/types.ts
  src/_redux/main/fileTree/index.ts
  src/_redux/main/fileTree/slice.ts
  src/_redux/main/fileTree/types.ts
  src/_redux/main/processor/slice.ts
  src/_redux/main/processor/types.ts
  src/_redux/main/types.ts
  src/_redux/useAppState.tsx
  src/components/main/actionsPanel/navigatorPanel/components/AdditionalPanel.tsx
  src/components/main/actionsPanel/navigatorPanel/helpers/helpers.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeViewState.ts
  src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx
  src/components/main/actionsPanel/workspaceTreeView/helpers/createFileOrFolder.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/deleteFileOrFolder.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/duplicateNode.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/index.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/moveActions.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/moveDirectory.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/renameNode.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/validateAndDeleteNode.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/validateAndMoveNode.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/index.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useFileOperations.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useInvalidNodes.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeViewState.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useSync.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useTemporaryNodes.ts
  src/components/main/stageView/iFrame/hooks/useCmdk.ts
  src/constants/main.ts
  src/pages/main/MainPage.tsx
  src/pages/main/helper.ts
  src/pages/main/hooks/index.ts
  src/pages/main/hooks/useCmdk.ts
  src/pages/main/hooks/useCmdkModal.ts
  src/pages/main/hooks/useCmdkReferenceData.ts
  src/pages/main/hooks/useFileHandlers.ts
  src/pages/main/hooks/useHandlers.ts
  src/pages/main/hooks/useInit.ts
  src/pages/main/hooks/usePanels.ts
  src/pages/main/hooks/useRecentProjects.ts
  src/pages/main/hooks/useReferenceData.ts
  src/pages/main/hooks/useReferences.ts
  src/pages/main/hooks/useRunningActions.ts
  src/pages/main/processor/helpers.ts
  src/pages/main/processor/hooks/useNodeTreeEvent.ts
Labels: enhancement

#511 #501
  src/_node/apis.ts
  src/_redux/main/context.ts
  src/_redux/main/nodeTree/slice.ts
  src/_redux/main/nodeTree/types.ts
  src/_redux/main/types.ts
  src/_redux/useAppState.tsx
  src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx
  src/components/main/actionsPanel/nodeTreeView/constants.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useCmdk.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionHandlers.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeTreeCallback.ts
  src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx
  src/components/main/codeView/CodeView.tsx
  src/components/main/codeView/helpers.ts
  src/components/main/codeView/hooks/useEditor.ts
  src/components/main/codeView/index.ts
  src/pages/main/MainPage.tsx
  src/pages/main/hooks/useReferences.ts
  src/pages/main/processor/hooks/useNodeTreeEvent.ts
Labels: enhancement

#513 #501
  src/_redux/main/codeView/slice.ts
  src/_redux/main/codeView/types.ts
  src/_redux/useAppState.tsx
  src/components/main/codeView/CodeView.tsx
  src/components/main/codeView/helpers.ts
  src/pages/main/processor/hooks/useNodeTreeEvent.ts
Labels: enhancement

#520 Copy, Cut , Paste, Duplicate
  src/_node/file/actions.ts
  src/_node/file/helpers.ts
  src/_node/file/types.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/duplicateNode.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/generateNewNameMoveNode.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/index.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/moveActions.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/moveFile.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/renameNode.ts
  src/components/main/actionsPanel/workspaceTreeView/helpers/validateAndMoveNode.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useFileOperations.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
Labels: enhancement

#524 Rename file
  src/_node/file/actions.ts
  src/_node/file/apis.ts
  src/_node/file/types.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/pages/main/hooks/useCmdk.ts
Labels: bug

#529 #528
  src/_node/file/helpers.ts
  src/_redux/main/context.ts
  src/_redux/main/fileTree/event/slice.ts
  src/_redux/main/fileTree/event/types.ts
  src/_redux/main/types.ts
  src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx
  src/components/main/actionsPanel/workspaceTreeView/hooks/index.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useInvalidNodes.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeViewState.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useTemporaryNodes.ts
  src/pages/main/MainPage.tsx
  src/pages/main/hooks/index.ts
  src/pages/main/hooks/useCmdk.ts
  src/pages/main/hooks/useCmdkModal.ts
  src/pages/main/hooks/useCmdkReferenceData.ts
  src/pages/main/hooks/useFileHandlers.ts
  src/pages/main/hooks/useHandlers.ts
  src/pages/main/hooks/useInit.ts
  src/pages/main/hooks/useInvalidFileNodes.ts
  src/pages/main/hooks/useReferenceData.ts
  src/pages/main/processor/helpers.ts
  src/pages/main/processor/hooks/useFileTreeEvent.ts
  src/pages/main/processor/hooks/useNodeTreeEvent.ts
  src/services/global.ts
  src/services/htmlapi.ts
  src/services/index.ts
Labels: enhancement

#530 change API structure for file actions
  src/_node/apis.ts
  src/_node/file/actions.ts
  src/_node/file/types.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/pages/main/processor/hooks/useFileTreeEvent.ts
Labels: enhancement

#533 cut/copy/paste, moveDnD, duplicate
  src/_node/file/FileSystemApis.ts
  src/_node/file/actions.ts
  src/_node/file/helpers.ts
  src/_node/helpers.ts
  src/_node/node/actions.ts
  src/_redux/main/fileTree/event/types.ts
  src/_redux/main/processor/types.ts
  src/components/main/actionsPanel/nodeTreeView/helpers/addNodeToTree.ts
  src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx
  src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts
  src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts
  src/components/main/codeView/helpers.ts
  src/pages/main/MainPage.tsx
  src/pages/main/helper.ts
  src/pages/main/hooks/useHandlers.ts
  src/pages/main/processor/helpers.ts
  src/pages/main/processor/hooks/useFileTreeEvent.ts
Labels: enhancement

#534 Node api structure
  src/_node/node/actions.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionHandlers.ts
  src/components/main/stageView/iFrame/helpers.ts
Labels: enhancement

#535 async/await fix for node actions
  src/_node/node/actions.ts
  src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionHandlers.ts
Labels: enhancement
